### PR TITLE
Recurrentshop 1

### PR DESCRIPTION
**Pull request by farizrahman4u**

### CODE REVIEW

**Comment by farizrahman4u** [comment]
@abhaikollara Please test recurrentshop-1 branch on TF backend.

**Comment by abhaikollara** [comment]
@farizrahman4u Weird, I'm getting segmentation faults on all three tests

**Comment by farizrahman4u** [comment]
Update TF and Keras to latest version.

**Comment by farizrahman4u** [comment]
All tests are passing for me on TF / python 3.5.. except for teacher forcing.

**Comment by abhaikollara** [comment]
No joy, here's traceback for `test_recurrent_sequential`
```
Traceback (most recent call last):
  File "tests/test_recurrent_sequential.py", line 219, in <module>
    model.fit([np.random.random((32, 7, 5)), np.random.random((32, 7, 5))], np.random.random((32, 5)))
  File "/home/abhai/keras/keras/engine/training.py", line 1486, in fit
    initial_epoch=initial_epoch)
  File "/home/abhai/keras/keras/engine/training.py", line 1141, in _fit_loop
    outs = f(ins_batch)
  File "/home/abhai/keras/keras/backend/tensorflow_backend.py", line 2101, in __call__
    session = get_session()
  File "/home/abhai/keras/keras/backend/tensorflow_backend.py", line 155, in get_session
    _initialize_variables()
  File "/home/abhai/keras/keras/backend/tensorflow_backend.py", line 308, in _initialize_variables
    sess.run(tf.variables_initializer(uninitialized_variables))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'recurrent_sequential_14/while_1/Variable_1/Assign' has inputs from different frames. The input 'recurrent_sequential_14/while_1/Const_1' is in frame 'recurrent_sequential_14/while_1/recurrent_sequential_14/while_1/'. The input 'recurrent_sequential_14/while_1/Variable_1' is in frame ''.
[1]    15461 segmentation fault  python tests/test_recurrent_sequential.py
```

**Comment by farizrahman4u** [comment]
Thats the test for teacherforcing failing. I think the rest of the file is commented out?

**Comment by abhaikollara** [comment]
I tried commenting out the teacher forcing part, now I get this

```
*** Error in `python': free(): invalid pointer: 0x000000000178e320 ***
[1]    21185 abort      python tests/test_recurrent_sequential.py
```

**Comment by farizrahman4u** [comment]
But did it train the rest of the models?

**Comment by abhaikollara** [comment]
Yeah, it did

**Comment by farizrahman4u** [comment]
cool. 
Next : Documentation.

**Comment by abhaikollara** [comment]
Hold on, I've been testing on python2.7

**Pull request merged**
